### ISSUE TITLE
[Idea] Show links location on map if possible.

### ISSUE THREAD

**Issue by SimplPixl** [Selene-T/Tracker-of-Time#3]
As a user I use the map tracker as a replacement for the mini map when streaming so my audience can see what checks we need.

Currently links location is not shown on this map.

Would be epic to have links location indicator (yellow for current and red for last place link entered on the current map) to display so that users don't have to rely on knowledge of the areas of the game and it can fully replace the mini map for streaming purposes.

Not sure if this data is able to be pulled from the game so just an idea!

**Comment by Selene-T** [comment]
This is a multi-layered issue. I can pull the player's location and display it on the minimap, which is currently only fully done while in the Haunted Wasteland. The player's location is also pulled while in Ganon's Castle to determine what part of it you are in, since the game normally does not track your room value.

I am currently working on learning c++ and rewriting the tracker from the ground up. I have not had much time to get on that though, but hopefully will be able to work more things into it with better speed.

**Comment by SimplPixl** [comment]
No stress, it's more a nice to have :) My audience loves the checks and it's more me wanting to see it especially when I'm backwalking and needing to line up across Hyrule field! I haven't got those areas yet in a playthrough so I'm excited to see what it looks like :)

**Comment by ZacharyCarey** [comment]
Let me know if you need some help! I am a fan of the project and would like to contribute if possible.
